/**
 * AgentLib Canonical Message Format v1.
 *
 * SPECIFICATION NOTE:
 * AgentLib Canonical Message Format v1 mirrors the OpenAI Responses API representation
 * (items: message, function_call, function_call_output, reasoning).
 *
 * All objects generated by constructors in this module are deep-frozen (Object.freeze)
 * to ensure memory and context immutability.
 */

/**
 * Deep freezes an object and its nested properties.
 *
 * @template T
 * @param {T} obj - The object to deep freeze.
 * @returns {Readonly<T>}
 */
export function deepFreeze(obj) {
    if (obj === null || typeof obj !== 'object') {
        return obj;
    }
    if (Object.isFrozen(obj)) {
        return obj;
    }
    Object.freeze(obj);
    for (const key of Object.keys(obj)) {
        const val = obj[key];
        if (val !== null && typeof val === 'object') {
            deepFreeze(val);
        }
    }
    return obj;
}

/**
 * Constructs a canonical conversational text message.
 *
 * @param {object} params
 * @param {string} [params.role='user'] - 'user' | 'assistant' | 'system'
 * @param {string} [params.text=''] - Text content
 * @param {string} [params.speaker] - Optional speaker / agent identifier
 * @param {string} [params.id] - Optional unique message identifier
 * @returns {object} Canonical text message item
 */
export function makeTextMessage({ role = 'user', text = '', content = undefined, speaker = undefined, id = undefined } = {}) {
    const messageContent = content !== undefined ? content : text;
    const msg = {
        type: 'message',
        role,
        content: messageContent,
    };
    if (speaker !== undefined) msg.speaker = speaker;
    if (id !== undefined) msg.id = id;
    return deepFreeze(msg);
}

/**
 * Constructs a canonical tool call request item.
 *
 * @param {object} params
 * @param {string} params.name - The name of the tool to invoke
 * @param {object|string} [params.args={}] - Arguments for the tool (object or JSON string)
 * @param {string} [params.callId] - Call ID
 * @param {string} [params.id] - Alias for Call ID
 * @returns {object} Canonical tool call item
 */
export function makeToolCall({ name, args = {}, arguments: rawArguments, callId, id } = {}) {
    const cid = callId || id;
    const resolvedArgs = rawArguments !== undefined ? rawArguments : args;
    const argumentsString = typeof resolvedArgs === 'string' ? resolvedArgs : JSON.stringify(resolvedArgs ?? {});
    const item = {
        type: 'function_call',
        call_id: cid,
        name,
        arguments: argumentsString,
    };
    if (id !== undefined) item.id = id;
    return deepFreeze(item);
}

/**
 * Constructs a canonical tool execution result item.
 * Stores value directly, owning single-encoding across the library.
 *
 * @param {object} params
 * @param {string} params.callId - Associated tool call ID
 * @param {string} [params.name] - Associated tool name
 * @param {any} [params.value] - Execution result value
 * @param {any} [params.output] - Alias for value
 * @returns {object} Canonical tool output item
 */
export function makeToolResult({ callId, name, value, output } = {}) {
    const val = value !== undefined ? value : output;
    const item = {
        type: 'function_call_output',
        call_id: callId,
        output: val,
    };
    if (name !== undefined) item.name = name;
    return deepFreeze(item);
}

/**
 * Constructs a canonical reasoning trace item.
 *
 * @param {object} params
 * @param {any} [params.summary] - High-level summary of reasoning
 * @param {any} [params.details] - Detailed reasoning content
 * @param {any} [params.content] - Alias for details
 * @returns {object} Canonical reasoning item
 */
export function makeReasoning({ summary, details, content } = {}) {
    const item = {
        type: 'reasoning',
        summary: summary || undefined,
        content: details !== undefined ? details : content,
    };
    return deepFreeze(item);
}

// ---------------------------------------------------------------------------
// Canonical Selectors
// ---------------------------------------------------------------------------

export function isToolCall(item) {
    return item !== null && typeof item === 'object' && item.type === 'function_call';
}

export function isToolResult(item) {
    return item !== null && typeof item === 'object' && item.type === 'function_call_output';
}

export function isTextMessage(item) {
    return item !== null && typeof item === 'object' && item.type === 'message';
}

export function isReasoning(item) {
    return item !== null && typeof item === 'object' && item.type === 'reasoning';
}

export function toolCallName(item) {
    return isToolCall(item) ? item.name : undefined;
}

export function toolCallId(item) {
    return isToolCall(item) ? (item.call_id || item.id) : undefined;
}

export function toolCallArgs(item) {
    if (!isToolCall(item)) return undefined;
    if (typeof item.arguments === 'object' && item.arguments !== null) {
        return item.arguments;
    }
    if (typeof item.arguments === 'string') {
        try {
            return JSON.parse(item.arguments);
        } catch {
            return item.arguments;
        }
    }
    return {};
}

export function messageText(item) {
    if (!item) return '';
    if (typeof item === 'string') return item;
    if (typeof item.text === 'string') return item.text;
    if (typeof item.content === 'string') return item.content;
    if (Array.isArray(item.content)) {
        const textParts = item.content
            .map((part) => {
                if (typeof part === 'string') return part;
                if (part && typeof part.text === 'string') return part.text;
                return '';
            })
            .filter(Boolean);
        return textParts.join('\n');
    }
    if (typeof item.output === 'string') return item.output;
    if (item.rawResponse?.output && Array.isArray(item.rawResponse.output)) {
        for (const out of item.rawResponse.output) {
            const text = messageText(out);
            if (text) return text;
        }
    }
    return '';
}

export function messageSpeaker(item) {
    return item?.speaker || item?.name || undefined;
}

export function messageRole(item) {
    return item?.role || undefined;
}
